# -*- coding: utf-8 -*-
"""task3_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_jEtvZcmo-meKIBzo1H99AfNXf7a5S3W
"""

import pandas as pd
import numpy as np
import os

df = pd.read_csv("data/trends_clean.csv")

print("Loaded data:", df.shape)
print(df.head())

print("\nAverage score:", int(df["score"].mean()))
print("Average comments:", int(df["num_comments"].mean()))

print("\nNumPy Stats:")
print("Mean:", int(np.mean(df["score"])))
print("Median:", int(np.median(df["score"])))
print("Std:", int(np.std(df["score"])))
print("Max:", int(np.max(df["score"])))
print("Min:", int(np.min(df["score"])))

cat = df["category"].value_counts()
print("\nMost stories in:", cat.idxmax(), "(", cat.max(), "stories)")

top = df.loc[df["num_comments"].idxmax()]
print("\nMost commented:", top["title"], "-", int(top["num_comments"]), "comments")

df["engagement"] = df["num_comments"] / (df["score"] + 1)
df["is_popular"] = df["score"] > df["score"].mean()

os.makedirs("data", exist_ok=True)
df.to_csv("data/trends_analysed.csv", index=False)

print("\nSaved to data/trends_analysed.csv")