# -*- coding: utf-8 -*-
"""task1_data_collections.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oHiIH0HAub1EGh76soN12qXxDWtaqgRI
"""

import requests
import json
import os
import datetime

def get_category(title):
    title = title.lower()

    if "ai" in title:
        return "technology"
    elif "war" in title:
        return "worldnews"
    elif "game" in title:
        return "sports"
    elif "space" in title:
        return "research"
    elif "movie" in title:
        return "entertainment"
    else:
        return "others"

url = "https://hacker-news.firebaseio.com/v0/topstories.json"
ids = requests.get(url).json()
ids = ids[:100]
data_list = []
for i in ids:
    item_url = f"https://hacker-news.firebaseio.com/v0/item/{i}.json"
    data = requests.get(item_url).json()
    if data is None:
        continue
    title = data.get("title", "")
    story = {
        "post_id": data.get("id"),
        "title": title,
        "category": get_category(title),
        "score": data.get("score", 0),
        "num_comments": data.get("descendants", 0),
        "author": data.get("by", ""),
        "collected_at": str(datetime.datetime.now())
    }

    data_list.append(story)
os.makedirs("data", exist_ok=True)
today = datetime.datetime.now().strftime("%Y%m%d")
filename = f"data/trends_{today}.json"
with open(filename, "w") as f:
    json.dump(data_list, f)
print("Collected", len(data_list), "stories. Saved to", filename)