# -*- coding: utf-8 -*-
"""task2_data_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oHiIH0HAub1EGh76soN12qXxDWtaqgRI
"""

import pandas as pd

df = pd.read_json("data/trends_20260410.json")
print("Loaded", len(df), "stories")

df = df.drop_duplicates(subset="post_id")
print("After removing duplicates:", len(df))

df = df.dropna(subset=["post_id", "title", "score"])
print("After removing nulls:", len(df))

df["score"] = df["score"].astype(int)
df["num_comments"] = df["num_comments"].astype(int)

df = df[df["score"] >= 5]
print("After removing low scores:", len(df))

df["title"] = df["title"].str.strip()

df.to_csv("data/trends_clean.csv", index=False)

print("Saved", len(df), "rows to data/trends_clean.csv")

print("\nStories per category:")
print(df["category"].value_counts())