# -*- coding: utf-8 -*-
"""task4_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oHiIH0HAub1EGh76soN12qXxDWtaqgRI
"""

import pandas as pd
import matplotlib.pyplot as plt
import os

df = pd.read_csv("data/trends_analysed.csv")
os.makedirs("outputs", exist_ok=True)
top10 = df.sort_values(by="score", ascending=False).head(10)
titles = top10["title"].str[:50]
scores = top10["score"]
plt.figure()
plt.barh(titles, scores)
plt.xlabel("Score")
plt.ylabel("Title")
plt.title("Top 10 Stories by Score")

plt.savefig("outputs/chart1_top_stories.png")
plt.close()

category_counts = df["category"].value_counts()

plt.figure()
plt.bar(category_counts.index, category_counts.values)
plt.xlabel("Category")
plt.ylabel("Number of Stories")
plt.title("Stories per Category")

plt.savefig("outputs/chart2_categories.png")
plt.close()

popular = df[df["is_popular"] == True]
not_popular = df[df["is_popular"] == False]

plt.figure()
plt.scatter(popular["score"], popular["num_comments"], label="Popular")
plt.scatter(not_popular["score"], not_popular["num_comments"], label="Not Popular")

plt.xlabel("Score")
plt.ylabel("Comments")
plt.title("Score vs Comments")
plt.legend()

plt.savefig("outputs/chart3_scatter.png")
plt.close()

fig, axes = plt.subplots(1, 3, figsize=(15, 5))

axes[0].barh(titles, scores)
axes[0].set_title("Top Stories")

axes[1].bar(category_counts.index, category_counts.values)
axes[1].set_title("Categories")

axes[2].scatter(popular["score"], popular["num_comments"], label="Popular")
axes[2].scatter(not_popular["score"], not_popular["num_comments"], label="Not Popular")
axes[2].set_title("Score vs Comments")
axes[2].legend()

plt.suptitle("TrendPulse Dashboard")

plt.savefig("outputs/dashboard.png")
plt.close()

print("✅ All charts saved in outputs folder")